jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
      # command to run tests
      script: true